### ISSUE TITLE
CSV/custom type response rendering

### ISSUE THREAD

**Issue by maxdubrinsky** [swaggest/rest#58]
In the process of migrating a project over to use this collection of modules, and was wondering if you may have any recommendations for handling non-json response types. So far it looks like I may have to build my own response encoder to take the `output` interface and render it properly, but I feel like that's boiling the ocean.

Any insight would be much appreciated, this module has solved so many problems for our project!

**Comment by vearutop** [comment]
Hi, there is no special support for CSV encoding. Recommended approach for such case is to manually stream content directly into response writer (and take care of response formatting).

This allows almost same flexibility as raw `http.Handler` and does not require to populate a full slice of data in advance (and occupy memory).

Please check the example:
https://github.com/swaggest/rest/blob/v0.2.20/_examples/advanced/router.go#L76-L77
https://github.com/swaggest/rest/blob/v0.2.20/_examples/advanced/output_writer.go

**Comment by vearutop** [comment]
Maybe it makes sense to introduce an interface/type to accommodate CSV response, but I don't have a good idea of how that could look like to be an improvement over manual streaming.

Something like for pre-populated data.
```go
type CSVRows [][]string
```


Or maybe something like this.
```go
	type output []struct {
		Field1 string `csv:"field1"`
		Field2 int    `csv:"field2"`
	}
```

**Comment by maxdubrinsky** [comment]
Thanks for getting back so quickly!

Using a `usecase.OutputWithEmbeddedWriter` should work for us and our implementation, although being able to use a `csv` tag would be a neat addition. Haven't seen many things that support that though, and we already built the `struct -> [][]string` converter so this was a quick transition.

Something I did notice though was now using the `header` tag on output no longer works? 

```
 panic: reflect.Value.Interface: cannot return value obtained from unexported field or method
INFO[0001] goroutine 52 [running]:
runtime/debug.Stack()
        /usr/local/Cellar/go/1.17.5/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/go-chi/chi/middleware.Recoverer.func1.1()
        /Users/max/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/recoverer.go:25 +0x7f
panic({0x195d060, 0x1c162e0})
        /usr/local/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1038 +0x215
reflect.valueInterface({0x1a7ca40, 0xc000110b00, 0x30}, 0xf8)
        /usr/local/Cellar/go/1.17.5/libexec/src/reflect/value.go:1362 +0xd9
reflect.Value.Interface(...)
        /usr/local/Cellar/go/1.17.5/libexec/src/reflect/value.go:1351
github.com/swaggest/form/v5.(*encoder).setFieldByType(0xc00020e050, {0x1a7ca40, 0xc000110b00, 0xc000110b00}, {0xc00003e7c0, 0x1c635d0, 0x19f6ee0}, 0x1ae4c11, 0x4)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:123 +0x3be
github.com/swaggest/form/v5.(*encoder).traverseStruct(0xc00020e050, {0x19f6ee0, 0xc000110b00, 0x10000000a7620f8}, {0xc00003e7c0, 0x0, 0x40}, 0x1014f25)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:60 +0x2b3
github.com/swaggest/form/v5.(*encoder).setFieldByType(0xc00020e050, {0x19e3d00, 0xc000139720, 0xc000139720}, {0xc00003e7c0, 0x1c635d0, 0x1a8b140}, 0x1ae4c11, 0x4)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:233 +0xc8a
github.com/swaggest/form/v5.(*encoder).traverseStruct(0xc00020e050, {0x1a8b140, 0xc000139720, 0x10000000a7620f8}, {0xc00003e7c0, 0x0, 0x40}, 0x1014f25)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:60 +0x2b3
github.com/swaggest/form/v5.(*encoder).setFieldByType(0xc00020e050, {0x19c8f00, 0xc0000e3100, 0xc0000e3100}, {0xc00003e7c0, 0x1c635d0, 0x19f81a0}, 0x1ae4c11, 0x4)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:233 +0xc8a
github.com/swaggest/form/v5.(*encoder).traverseStruct(0xc00020e050, {0x19f81a0, 0xc0000e3100, 0x10001000a7620f8}, {0xc00003e7c0, 0x0, 0x40}, 0x1014f25)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:60 +0x2b3
github.com/swaggest/form/v5.(*encoder).setFieldByType(0xc00020e050, {0x19f81a0, 0xc0000e3100, 0xc0000e3100}, {0xc00003e7c0, 0x1c635d0, 0x1a315e0}, 0x1ae4c11, 0x4)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:233 +0xc8a
github.com/swaggest/form/v5.(*encoder).traverseStruct(0xc00020e050, {0x1a315e0, 0xc0000e3100, 0xc0004bc8b0}, {0xc00003e7c0, 0x0, 0x40}, 0x0)
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/encoder.go:60 +0x2b3
github.com/swaggest/form/v5.(*Encoder).Encode(0xc0005222d0, {0x19d3be0, 0xc0000e3100}, {0x0, 0x0, 0x5a000})
        /Users/max/go/pkg/mod/github.com/swaggest/form/v5@v5.0.1/form_encoder.go:133 +0x2b7
github.com/swaggest/rest/response.(*writerWithHeaders).setHeaders(0xc000139720)
        /Users/max/go/pkg/mod/github.com/swaggest/rest@v0.2.19/response/encoder.go:327 +0x5c
github.com/swaggest/rest/response.(*writerWithHeaders).Write(0xc000139720, {0xc0001c0000, 0x1000, 0x1000})
        /Users/max/go/pkg/mod/github.com/swaggest/rest@v0.2.19/response/encoder.go:343 +0x45
bufio.(*Writer).Flush(0xc0004f48d0)
        /usr/local/Cellar/go/1.17.5/libexec/src/bufio/bufio.go:607 +0x62
bufio.(*Writer).WriteString(0xc0004f48d0, {0xc0005b4460, 0x1f})
        /usr/local/Cellar/go/1.17.5/libexec/src/bufio/bufio.go:711 +0x30
encoding/csv.(*Writer).Write(0xc0004f4848, {0xc00031fb30, 0xf, 0x0})
        /usr/local/Cellar/go/1.17.5/libexec/src/encoding/csv/writer.go:63 +0x169
encoding/csv.(*Writer).WriteAll(0xc0004f4848, {0xc000d4a000, 0x3e9, 0x0})
        /usr/local/Cellar/go/1.17.5/libexec/src/encoding/csv/writer.go:137 +0x71
```

**Comment by vearutop** [comment]
Headers should be working ok, as in example https://github.com/swaggest/rest/blob/v0.2.20/_examples/advanced/output_writer.go#L23.

From the panic message it seems some of the fields are unexported and therefore have limited availability to reflect.
Could you share your output structure?

**Comment by vearutop** [comment]
Hm, weird, I can not reproduce the issue with headers.
https://go.dev/play/p/uXyLa2eYHWe

```go
package main

import (
	"context"
	"encoding/csv"
	"log"
	"net/http"
	"net/http/httptest"

	"github.com/swaggest/rest/nethttp"
	"github.com/swaggest/rest/web"
	"github.com/swaggest/usecase"
)

type Risk struct {
	Foo string `json:"foo"`
}

type RiskList struct {
	Total    uint   `json:"total" header:"X-Total" example:"9001"`
	NextPage int    `json:"nextPage,omitempty" header:"X-Next-Page" example:"2"`
	Risks    []Risk `json:"risks"`
}

type Response struct {
	usecase.OutputWithEmbeddedWriter
	RiskList
}

func main() {
	u := usecase.NewIOI(nil, new(Response), func(ctx context.Context, input, output interface{}) error {
		out := output.(*Response)

		out.Total = 123
		out.NextPage = 321

		c := csv.NewWriter(out)
		return c.WriteAll([][]string{{"abc", "def", "hij"}, {"klm", "nop", "qrs"}})
	})

	s := web.DefaultService()
	s.Get("/csv", u, nethttp.SuccessfulResponseContentType("text/csv; charset=utf-8"))

	req, err := http.NewRequest(http.MethodGet, "/csv", nil)
	if err != nil {
		log.Fatal(err)
	}

	rw := httptest.NewRecorder()

	s.ServeHTTP(rw, req)

	log.Println("Status:", rw.Code)
	log.Println("Body:", rw.Body.String())
	log.Println("X-Total:", rw.Header().Get("X-Total"))
	log.Println("X-Next-Page:", rw.Header().Get("X-Next-Page"))
}
```
```
2009/11/10 23:00:00 Status: 200
2009/11/10 23:00:00 Body: abc,def,hij
klm,nop,qrs

2009/11/10 23:00:00 X-Total: 123
2009/11/10 23:00:00 X-Next-Page: 321
```

**Comment by vearutop** [comment]
Please reopen this issue if it is still reproducible.
